### ISSUE TITLE
Переделать, чтобы не было каждый раз && limit

### ISSUE THREAD

**Issue by coursar** [Artyom16RUS/Sport-Master#1]
https://github.com/Artyom16RUS/Sport-Master/blob/c0b716e5df9ab6b95a037e35a9e9244e386467e1/src/Main.java#L24-L36

**Comment by Artyom16RUS** [comment]
Changed: made a repeating **_limit_** in a detached constructions

https://github.com/Artyom16RUS/Sport-Master/blob/21c8a3a20eab0c95f9afdf75eb997a4be5b4139f/src/Main.java#L37-L44
