### ISSUE TITLE
Строка (double) balance / 100 повторяется три раза

### ISSUE THREAD

**Issue by coursar** [Artyom16RUS/Sport-Master#2]
https://github.com/Artyom16RUS/Sport-Master/blob/c0b716e5df9ab6b95a037e35a9e9244e386467e1/src/Main.java#L26

**Comment by Artyom16RUS** [comment]
Changed: made a repeating **_double_** in a detached construction 

https://github.com/Artyom16RUS/Sport-Master/blob/21c8a3a20eab0c95f9afdf75eb997a4be5b4139f/src/Main.java#L42-L44

**Comment by Artyom16RUS** [comment]
Прошу проверить исправления. В список выполненых работ не засчитана.

**Comment by Artyom16RUS** [comment]
Closes #2
