### ISSUE TITLE
На будущее - со сканера можно читать int

### ISSUE THREAD

**Issue by coursar** [Artyom16RUS/Sport-Master#3]
https://github.com/Artyom16RUS/Sport-Master/blob/21c8a3a20eab0c95f9afdf75eb997a4be5b4139f/src/Main.java#L17

**Comment by Artyom16RUS** [comment]
Да, знаю об этом. Но в сканере человек водит число с точкй и его надо проиброзовать без потери в int. То есть цена с учетом копеек.
